imports:
- path: vm-template.py
- path: firewall-template.py
- path: compute-engine-template.py

resources:
- name: compute-engine-setup
  type: compute-engine-template.py
  properties:
    projectId: helpful-compass-282814
    etlApiVm: etl-api-vm
    machineType: n1-standard-2
    zone: europe-west1-b
    secretsBucket: raghu-decis-etl-01-dev-server-secrets    
    startupBucket: raghu_etl_dev_bucket/startup
    repo: airflowvm_2
    branch: raghu_branch_01
